from tkinter import *
import tkinter as tk
from PIL import Image,ImageTk
jkl=tk.Tk()
jkl.geometry('5000x5000')
jkl.configure(bg='light yellow')
jkl.title('https://hotel.org')
img=Image.open("xyz.jpg","r")
test=ImageTk.PhotoImage(img)
i1=tk.Label(image=test,height=3240,width=1800)
i1.img=test
i1.place(x=0,y=0)
x1=Label(jkl,text='welcome to \n RESTUARANT SAVIRUCHI',height=2,width=18,bg='light yellow',fg='black',font=('algerian',25))
x1.place(x=400,y=0)
x2=Label(jkl,text='Pure veg',height=2,width=13,bg='light yellow',fg='green',font=('algerian',15))
x2.place(x=750,y=20)
x2=Label(jkl,text='NAME',height=2,width=13,bg='light yellow',fg='green',font=('algerian',15))
x2.place(x=50,y=100)
x2=Label(jkl,text='CONTACT NUMBER',height=2,width=18,bg='light yellow',fg='green',font=('algerian',15))
x2.place(x=50,y=200)
x2=Entry(jkl,text='',bg='light yellow',fg='green',font=('algerian',15))
x2.place(x=200,y=150)
x2=Entry(jkl,text='',bg='light yellow',fg='green',font=('algerian',15))
x2.place(x=200,y=250)
def st():
    abc=tk.Tk()
    abc.geometry('5000x5000')
    abc.configure(bg='light yellow')
    abc.title('https://hotel.org')
    x1=Label(abc,text='RESTUARANT RUCHI',height=2,width=18,bg='light yellow',fg='black',font=('algerian',25))
    x1.place(x=400,y=0)
    x1=Label(abc,text='Nothing brings \n people together \n like a \n good FOOD',height=10,width=18,bg='light yellow',fg='black',font=('freestyle script',30))
    x1.place(x=500,y=100)
    x2=Label(abc,text='Pure veg',height=2,width=13,bg='light yellow',fg='green',font=('algerian',15))
    x2.place(x=750,y=20)
    x3=Label(abc,text='Menu',height=2,width=13,bg='light yellow',fg='red',font=('blackadder itc',25))
    x3.place(x=30,y=40)
    x3=Label(abc,text='Thank you',height=2,width=13,bg='light yellow',fg='red',font=('blackadder itc',30))
    x3.place(x=450,y=520)
    x3=Label(abc,text='visit again',height=2,width=13,bg='light yellow',fg='red',font=('blackadder itc',25))
    x3.place(x=700,y=540)

    def a():
        xyz=tk.Tk()
        xyz.geometry('500x500')
        xyz.configure(bg='light blue')
        x2=Label(xyz,text=' Filter Coffee\n[price - 90]\n\n\nMay your \n COFFEE \n be strong\n and your \n MONDAYS \n be short ',height=10,width=13,bg='light blue',fg='black',font=('freestyle script',20))
        x2.place(x=20,y=20)
    def b():
        xyz=tk.Tk()
        xyz.geometry('500x500')
        xyz.configure(bg='light blue')
        x=Label(xyz,text='Green Tea\n[price - 90]\n\n\nWould you like an adventure now\nor shall we have our TEA first',height=10,width=25,bg='light blue',fg='black',font=('freestyle script',20))
        x.place(x=20,y=20)
    def c():
        xyz=tk.Tk()
        xyz.geometry('500x500')
        xyz.configure(bg='light blue')
        x=Label(xyz,text='Garlic Bread\n[price - 130]\n\n\nSometimes you just gotta\n eat GARLIC BREAD\n and MOVE ON',height=10,width=20,bg='light blue',fg='black',font=('freestyle script',20))
        x.place(x=20,y=20)
    def d():
        xyz=tk.Tk()
        xyz.geometry('500x500')
        xyz.configure(bg='light blue')
        x=Label(xyz,text='Veg Burger\n[price - 120]\n\n\n"Better to wait a little for your BURGER\nthan to have your burger wait\n along time for you"',height=10,width=30,bg='light blue',fg='black',font=('freestyle script',20))
        x.place(x=20,y=20)
    def e():
        xyz=tk.Tk()
        xyz.geometry('500x500')
        xyz.configure(bg='light blue')
        x=Label(xyz,text='Paneer sandwich\n[price - 130]\n\n\nFRIENDS\n buy you a sandwich\n BEST FRIENDS\neat your sandwich',height=10,width=15,bg='light blue',fg='black',font=('freestyle script',20))
        x.place(x=20,y=20)
    def f():
        xyz=tk.Tk()
        xyz.geometry('500x500')
        xyz.configure(bg='light blue')
        x=Label(xyz,text='Milk shake\n[price - 90]\n\n\nIn era of HEADSHAKE\n and HANDSHAKE\n i prefer\nMILKSHAKE',height=10,width=20,bg='light blue',fg='black',font=('freestyle script',20))
        x.place(x=20,y=20)
    
    b1=Button(abc,text='1. Filter Coffee',command=a,height=1,width=13,bg='light yellow',fg='green',font=('comic sans ms',15))
    b1.place(x=60,y=110)
    b2=Button(abc,text='2. Green Tea',command=b,height=1,width=10,bg='light yellow',fg='green',font=('comic sans ms',15))
    b2.place(x=60,y=180)
    b3=Button(abc,text='3. Garlic Bread',command=c,height=1,width=13,bg='light yellow',fg='green',font=('comic sans ms',15))
    b3.place(x=60,y=250)
    b4=Button(abc,text='4. Veg Burger',command=d,height=1,width=13,bg='light yellow',fg='green',font=('comic sans ms',15))
    b4.place(x=60,y=320)
    b5=Button(abc,text='5. Paneer sandwich',command=e,height=1,width=15,bg='light yellow',fg='green',font=('comic sans ms',15))
    b5.place(x=60,y=390)
    b6=Button(abc,text='6. Milk shake',command=f,height=1,width=10,bg='light yellow',fg='green',font=('comic sans ms',15))
    b6.place(x=60,y=460)

b=Button(jkl,text='submit',command=st,bg='green',fg='black',height=2,width=10)
b.place(x=50,y=350)


