#l1=[1,2,3,4]
#l2=slice(2)
#print(l1[l2])
#a=[1,2,3.4,4]
#a.append(3)
#print (a)
#b=a.clear()
#print (b)
#a=slice(2)
#print(l1[a])
#l1.insert(2,6)
#print(l1)
#l1.remove(3)
#print (l1)
#l1.sort ()
#print(l1)
#a=input("enter your name")
#print(a)
#b=input("enter your age")
#print(b)
#age=int(input("your age"))
#print(age)
#a=input("enter your age")
#b=input("enter your name")
#c=input('your age is',str(b))
#print(c)
#print(b)
