from tkinter import *
import tkinter as tk
window=tk.Tk()
window.geometry("1250x1250")
window.title('gambling')
window.configure(background='white')
L1=Label(window,text="Name",bg="black",fg="white",height=2,width=25,font=('CASTELLAR',19))
L1.place(x=10,y=150)
L2=Label(window,text="Darshan",bg="black",fg="white",height=2,width=25,font=('CASTELLAR',19))
L2.place(x=750,y=150)
L3=Label(window,text="USN",bg="black",fg="white",height=2,width=25,font=('CASTELLAR',19))
L3.place(x=10,y=300)
L4=Label(window,text="1DB19EC036",bg="black",fg="white",height=2,width=25,font=('CASTELLAR',19))
L4.place(x=750,y=300)
L5=Label(window,text="COLLEGE",bg="black",fg="white",height=2,width=25,font=('CASTELLAR',19))
L5.place(x=10,y=450)
L6=Label(window,text="DBIT",bg="black",fg="white",height=2,width=25,font=('CASTELLAR',19))
L6.place(x=750,y=450)
img=Image.open("abc.jpg","r")
test=ImageTk.PhotoImage(img)
i1=tk.Label(image=test,height=200,width=200)
i1.img=test
i1.place(x=300,y=50)
def submit():
    window=tk.Tk()
    window.geometry("1250x1250")
    window.title('gambling')
    window.configure(background='white')
    L7=Label(window,text="successfully submitted",bg="black",fg="white",height=2,width=25,font=('CASTELLAR',19))
    L7.place(x=750,y=450)
B1=Button(window,text="Napster",bg="light blue",fg="black",height=2,width=25,command=submit,font=('bold',21))
B1.place(x=400,y=700)
